### ISSUE TITLE
Thermostat Schedule, Fan, and Equipment

### ISSUE THREAD

**Issue by b0tt0mturn** [aneisch/thermostat_api_server_docker#5]
First off, thanks so much for this. I've got an HVAC imbalance in my home and I've been using your server code and HA to run the fan at various levels depending on temperature delta to equalize rooms temperatures - it's made a huge difference. So far it's been completely stable. 

Here is a list of things that have been minor issues for me:

1) The Schedule on the Observer gets reset within 12 hours. The Observer Wake, Home, Evening, Sleep settings get set to 69 or 71 degrees and the schedule is also reset to some default - I can't for the life of me figure out how or why. I can set automations in HA to hold temperature during certain time triggers, but that is not as family friendly as setting the schedule on the Observer.

2) The Observer has high, med and low fan settings, but the Thermostat entity only has high and low - can the medium setting be added?

3) Finally, it would be nice to know how often and how long the heat, aux heat (its a heat pump) and cool run for. I assume that is the Active Equipment Event, but that seems to be broken. 

Thanks again for all your work on this.

**Comment by aneisch** [comment]
1. I suspect this might be due to the response we send the thermostat when it asks for the config. I'll look into how we might read in the current program on first connect, and then spit that back out instead of responding with a "blank" one. I run my thermostat in Hold mode, so this has never come up as an issue for me. 

I see a bug here also where 71 is set in place of {candidate_configuration["htsp"]} in  (fixed https://github.com/aneisch/thermostat_api_server_docker/commit/b8bc4354e6c1e5eeea8aa81bc647610114c257a6). Does this fix the issue for you?

![301946155-5d54cbfc-b588-4b93-bfa3-f134acc3840a](https://github.com/aneisch/thermostat_api_server_docker/assets/6991461/07f1e7c5-489c-4140-b306-474d5f675bd9)


2. Added in https://github.com/aneisch/thermostat_api_server_docker/commit/362ff775fa8b7166301fa75686e86a7f4be44d2e. Thanks for pointing this out!

3. Active equipment events are things like failures or faults. Things you _don't_ want to see, such as when the capacitor in my outdoor unit failed in the middle of summer:
![Screen Shot 2024-02-02 at 1 14 40 PM](https://github.com/aneisch/thermostat_api_server_docker/assets/6991461/50ca628d-14d2-4a89-a062-d640ba20d286)

I use a history_stats sensor to track runtime:

```
- platform: history_stats
  name: ac_runtime_today_cool
  entity_id: sensor.thermostat_state
  state: "Cooling"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: ac_runtime_today_heat
  entity_id: sensor.thermostat_state
  state: "Heating"
  type: time
  start: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  end: "{{ now() }}"

- platform: history_stats
  name: ac_runtime_yesterday_cool
  entity_id: sensor.thermostat_state
  state: "Cooling"
  type: time
  end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  duration:
    hours: 24

- platform: history_stats
  name: ac_runtime_yesterday_heat
  entity_id: sensor.thermostat_state
  state: "Heating"
  type: time
  end: "{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}"
  duration:
    hours: 24
```
